### ISSUE TITLE
what's the purple block mean ?

### ISSUE THREAD

**Issue by baozidai** [faradey8951/SDI#18]
![image](https://user-images.githubusercontent.com/8564451/182033436-f8a4e3de-c08f-42c6-aa1e-15b3b2f9f544.png)
This is version 0.3 open beta

**Comment by faradey8951** [comment]
![image](https://user-images.githubusercontent.com/35138681/182105683-a814948d-b475-4ba8-8619-a4affc8168d2.png)

**Comment by faradey8951** [comment]
Current outdated project will be closed soon. A new one going, and it's much easier to manage with it. Stereo (double density) encoding feature also announced. It's 50% complete!

**Comment by faradey8951** [comment]
![image](https://user-images.githubusercontent.com/35138681/182106476-3275bb0c-b76b-42e2-a4f8-f385e32615e3.png)
New main window. All the data decoded gonna be placed onto table. It is possible to edit it and redecode if needed. Now all the data is going to be storing in the RAM and possible to be saved to disk drive
